name: Browser Tests

on:
  workflow_call:

jobs:
  browser:
    name: Browser Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup JS environment
        uses: ./.github/actions/setup-js
        with:
          playwright: "true"

      - name: Browser tests
        run: bun run test:browser

      - name: Upload report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ !cancelled() }}
        with:
          name: browser-test-report
          path: playwright-report/
          retention-days: 90
